name: Beholder HID Bot CD

on:
  workflow_dispatch:
  pull_request:
    branches: 
      - master
    paths:
      - 'beholder-hid-bot/**'
      - '!beholder-hid-bot/README.md'
      - '!beholder-hid-bot/docs/**'

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./beholder-hid-bot
      cache-key: beholder-hid-bot-pr
    
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.working-directory }}

    strategy:
      matrix:
        dotnet-version: ['6.x']

    steps:
      -
        uses: actions/checkout@v2
      - 
        name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - 
        name: Install dependencies
        run: dotnet restore --runtime linux-arm64
      - 
        name: Build
        run: dotnet publish --configuration Release --no-restore --runtime linux-arm64 --no-self-contained
      -
        name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: beholder-hid-bot-arm64
          path: ${{ github.workspace }}/beholder-hid-bot/bin/Release/net6.0/linux-arm64/publish/
      - 
        name: gzip artifacts
        run: gzip -r beholder-hid-bot-arm64.tar.gz ${{ github.workspace }}/beholder-hid-bot/bin/Release/net6.0/linux-arm64/publish/
      -
        name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: CD Build
          body: Continuous Delivery Build
          prerelease: true
          files: beholder-hid-bot-arm64.tar.gz


      